### ISSUE TITLE
Can't find executable appraisal for gem appraisal

### ISSUE THREAD

**Issue by evbuk1** [thoughtbot/appraisal#210]
When I run

`bundle exec appraisal install`

I receive the following error:

```
Traceback (most recent call last):
        4: from /usr/share/rvm/gems/ruby-2.7.4/bin/ruby_executable_hooks:22:in `<main>'
        3: from /usr/share/rvm/gems/ruby-2.7.4/bin/ruby_executable_hooks:22:in `eval'
        2: from /usr/share/rvm/gems/ruby-2.7.4/bin/appraisal:23:in `<main>'
        1: from /usr/share/rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/bundler/rubygems_integration.rb:402:in `block in replace_bin_path'
/usr/share/rvm/rubies/ruby-2.7.4/lib/ruby/2.7.0/bundler/rubygems_integration.rb:374:in `block in replace_bin_path': can't find executable appraisal for gem appraisal (Gem::Exception)
```

My appraisal file looks as follows:

```
if RUBY_VERSION < '1.9'
  appraise 'activerecord_2_2' do
    gem 'activerecord', '~> 2.2.0'
    gem 'factory_girl', '~> 2.3.0'
    gem 'rake', '~> 0.8.7'
  end
end

appraise 'activerecord_2_3' do
  gem 'activerecord', '~> 2.3.0'
end

appraise 'activerecord_3_0' do
  gem 'activerecord', '~> 3.0.0'
end

appraise 'activerecord_3_1' do
  gem 'activerecord', '~> 3.1.0'
end

appraise 'activerecord_3_2' do
  gem 'activerecord', '~> 3.2.0'
end

if RUBY_VERSION >= '1.9'
  appraise 'activerecord_4_0' do
    gem 'activerecord', '~> 4.0.0'
    gem 'mysql', '~> 2.9.0' if ENV['DB'] == 'mysql'
    gem 'protected_attributes', '~> 1.0.0'
  end

  appraise 'activerecord_4_1' do
    gem 'activerecord', '~> 4.1.0'
    gem 'mysql', '~> 2.9.0' if ENV['DB'] == 'mysql'
    gem 'protected_attributes', '~> 1.0.0'
  end
end
```

This is an old project that I am updating but I don't have an idea about the error above.  Can someone point me in the right direction please?

**Comment by nickcharlton** [comment]
Which version of bundler are you using?

What do you get if you install Appraisal from `main`? We might've fixed it by now, but it's hard to tell!

**Comment by pkuczynski** [comment]
@nickcharlton seems that @y-yagi is correct and it works from main. We would appreciate a release of a new version of the gem...

**Comment by nickcharlton** [comment]
Ah hah, okay cool. I'm looking at doing a new release today/tomorrow so that's good.

Thanks everyone for the reports and input here!
