### ISSUE TITLE
appraisal install problem with finding bundler gem

### ISSUE THREAD

**Issue by gazay** [thoughtbot/appraisal#87]
I think this problem somehow exists because of my environment but I can't find it quickly.
- I've created new repo for testing my own gem against different versions of other gems
- I fill `Appraisals` file:
```
appraise "rails-3" do
  gem "rails", "3.2.21"
end

appraise "rails-4-0" do
  gem "rails", "4.0.13"
end

appraise "rails-4-1" do
  gem "rails", "4.1.9"
end

appraise "rails-4-2" do
  gem "rails", "4.2.0"
end
```
- When I run `appraisal install` I get following error:
```bash
0:gon_tests:[master ✗]$ appraisal install
WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
>> bundle check --gemfile='/Users/alex/code/gon_tests/gemfiles/rails_3.gemfile' || bundle install --gemfile='/Users/alex/code/gon_tests/gemfiles/rails_3.gemfile'
/Users/alex/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/dependency.rb:298:in `to_specs': Could not find 'bundler' (>= 0) among 65 total gem(s) (Gem::LoadError)
	from /Users/alex/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/dependency.rb:309:in `to_spec'
	from /Users/alex/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:53:in `gem'
	from /Users/alex/.gem/ruby/2.1.5/bin/bundle:22:in `<main>'
/Users/alex/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/dependency.rb:298:in `to_specs': Could not find 'bundler' (>= 0) among 65 total gem(s) (Gem::LoadError)
	from /Users/alex/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/dependency.rb:309:in `to_spec'
	from /Users/alex/.rubies/ruby-2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:53:in `gem'
	from /Users/alex/.gem/ruby/2.1.5/bin/bundle:22:in `<main>'
```
- But if I run command from announce manually it just works:
```
0:gon_tests:[master ✗]$ bundle check --gemfile='/Users/alex/code/gon_tests/gemfiles/rails_3.gemfile' || bundle install --gemfile='/Users/alex/code/gon_tests/gemfiles/rails_3.gemfile'
The Gemfile's dependencies are satisfied
```

Do you have any idea how I can trace the problem?

**Comment by sikachu** [comment]
Hi @gazay. Are you vendoring your gems by any chance? We currently have some limitation with vendoring gem because Bundler decides not to vendor itself when you install your gem in vendored location. (#30)

**Comment by gazay** [comment]
Yes, this was the problem. Thank you.
